### ISSUE TITLE
please add a LICENSE file

### ISSUE THREAD

**Issue by waldenn** [sahajsk21/Anvesha#1]
Hi, please add a license file.

Thanks for this interesting wikidata project!

**Comment by sahajk21** [comment]
Done. Thanks.

**Comment by waldenn** [comment]
Hi Sahaj, I integrated your drill-down tool into the conzept encyclopedia project: [see here](https://conze.pt/explore/House?l=en&t=link-split&s=true&i=3947&u=https%3A%2F%2Fconze.pt%2Fapp%2Fbrowse%2F%3Fl%3Den%26c%3DQ3947)

Code here: https://github.com/waldenn/browse

I added some language control (with a URL parameter) to the SPARQL queries, replaced as much of the english text with icons, and added back button.
