### ISSUE TITLE
have you looked at Freebase Parallax?

### ISSUE THREAD

**Issue by danbri** [sahajsk21/Anvesha#2]
https://wikidatawalkabout.org/ is really nicely done! It reminds me of an old project from Metaweb, which was built on Freebase, called Parallax. It emphasised set-based navigation, which you're kind of doing here too. I think the best reference is this video: https://vimeo.com/1513562

(feel free to close this issue, I was going to try to ask on Twitter but this was easier to find... -- @danbri )

**Comment by yaronkoren** [comment]
Hi @danbri ! I remember seeing that video when it came out. Is there anything specifically you think should be copied from Parallax, or did you just want to note the similarity?

**Comment by danbri** [comment]
I have always thought that the explicit set-based navigation paradigm from Parallax was potentially very important to RDF data navigation, and it seems that you have something with element of it in wikidatawalkabout. I do not have specific proposals except that I'd be interested to hear if you have tried to do more in that direction (using Wikidata), since I also have a couple of intern projects on related issues right now.

**Comment by yaronkoren** [comment]
I think this can be closed.
